name: Lint, Test, Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
        name: Checkout branch
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: supercharge/mongodb-github-action@1.3.0
        name: Starting MongoDB
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Lint
        run: |
          npm ci
          npm run lint

      - name: Test
        run: npm run test
        env:
          MONGO_URI: mongodb://localhost:27017/cinema-ticket
